module xyz {
    module fluxinc {
        module noxmonitoring {
            module corba {

                exception IllegalSensorAccessException {
                    string reason;
                };

                exception IllegalStationAccessException {
                    string reason;
                };

                enum MonitorType {
                    nitrous_oxide
                };

                struct LogEntry {
                    string location;
                    MonitorType type;
                    double value;
                };

                typedef sequence<MonitorType> MonitorTypeSequence;
                typedef sequence<LogEntry> LogSequence;

                interface MonitorStation {
                    MonitorTypeSequence get_available_sensors() raises(IllegalStationAccessException);
                    double get_sensor_value(in MonitorType sensor) raises(IllegalSensorAccessException, IllegalStationAccessException);
                    string get_location();
                    /** Extra Function - Enable/Disable Stations/Servers **/
                    void enable_sensor(in MonitorType sensor) raises(IllegalSensorAccessException, IllegalStationAccessException);
                    void enable_station() raises(IllegalStationAccessException);

                    boolean is_disabled();

                    void disable_sensor(in MonitorType sensor) raises(IllegalSensorAccessException, IllegalStationAccessException);
                    void disable_station() raises(IllegalStationAccessException);
                };

                typedef sequence<MonitorStation> MonitorStationSequence;

                interface LocalControlServer {
                    void register();
                    void deregister();
                    MonitorStationSequence get_available_stations();
                    void report_value(in MonitorStation station, in MonitorType type, in double sensor_value);
                    LogSequence get_logs();
                };

                interface CentralControl {
                    void register();
                    void deregister();
                    void confirmed_alarm(in LocalControlServer server);
                };
            };
        };
    };
};